name: Daily Data Pipeline

on:
  schedule:
    - cron: "0 12 * * *"  # Runs daily at 12:00 UTC
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Load environment variables from GitHub Secret
        run: echo -e "${{ secrets.ENV_FILE }}" > .env
        # NOTE: using `-e` here so \n gets interpreted as newlines

      - name: Run Data Pipeline
        run: python src/pipeline.py

      - name: Run Quality Check
        run: python src/data_quality.py

      - name: Run Anomaly Detection
        run: python src/anomaly_detection.py

      - name: Commit updated data files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/
          git diff --quiet && echo "✅ No changes to commit" || (git commit -m "🔄 Daily data update" && git push)
